// Confirm why this is necessary. Can we make this list smaller?
export const backgrounds = [
  "Contabilidad",
  "Ingeniería aeroespacial",
  "Agricultura",
  "Antropología",
  "Arqueología",
  "Arquitectura",
  "Artes",
  "Ingeniería automotriz",
  "Bioingeniería",
  "Biología",
  "Ciencias biomédicas",
  "Administración de empresas",
  "Ingeniería química",
  "Química",
  "Ingeniería civil",
  "Comunicación y periodismo",
  "Ingeniería en Sistemas Computacionales",
  "Diseño",
  "Ciencias de la Tierra",
  "Ecología",
  "Economía",
  "Educación",
  "Ingeniería eléctrica",
  "Ingeniería electrónica",
  "Emprendimiento",
  "Ingeniería ambiental",
  "Finanzas",
  "Ingeniería alimentaria",
  "Ciencias de la alimentación",
  "Geografía",
  "Diseño gráfico",
  "Ciencias de la salud",
  "Historia",
  "Recursos humanos",
  "Diseño industrial",
  "Ingeniería industrial",
  "Relaciones internacionales",
  "Comercio internacional",
  "Idiomas",
  "Derecho",
  "Lingüística",
  "Literatura",
  "Logística",
  "Marketing",
  "Ingeniería de materiales",
  "Matemáticas",
  "Ingeniería mecánica",
  "Artes multimedia",
  "Medicina",
  "Ciencias militares",
  "Música",
  "Nanotecnología",
  "Enfermería",
  "Nutrición",
  "Ingeniería petrolera",
  "Filosofía",
  "Física",
  "Ciencias políticas",
  "Psicología",
  "Administración pública",
  "Relaciones públicas",
  "Trabajo social",
  "Sociología",
  "Desarrollo de software y programación",
  "Deportes",
  "Estadística",
  "Sostenibilidad",
  "Ingeniería de sistemas y computación",
  "Ingeniería de telecomunicaciones",
  "Teatro",
  "Turismo y gestión hotelera",
  "Veterinaria",
  "Otro",
];
