name = "ogx-signup-form"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
AIESEC_COUNTRY_ID = "1589"
EXPA_SIGNUP_URL = "https://auth.aiesec.org/users.json"

[secrets]
required = ["TURNSTILE_SECRET_KEY"]

[[d1_databases]]
binding = "DB"
database_name = "prod-ogx-signups"
database_id = "e0f7f9f7-df69-4f24-b279-30953d4a4f9f"

[observability.logs]
enabled = true
invocation_logs = true

[placement]
mode = "smart"
