// This list is different from the one in the Global Signup Form. Let's verify it with the marketing team
// We should have another way of specifying "Other" universities
export const universities = [
  "Instituto Tecnológico de Monterrey Campus Aguascalientes",
  "Universidad Autónoma de Aguascalientes",
  "Universidad del Valle de México - UVM(Campus Aguascalientes)",
  "Universidad Cuahutemoc campus Aguascalientes",
  "Global University",
  "Universidad Politécnica de Aguascalientes",
  "Universidad Concordia",
  "Instituto Tecnológico de Aguacalientes",
  "Escuela bancaria comercial campus Aguascalientes",
  "Universidad Panamericana campus Aguascalientes",
  "Universidad Tecnológicadel Norte de Aguascalientes",
  "Universidad Tecnológica del Retoño",
  "Universidad Tecnológica de Aguascalientes",
  "Otra Universidad de Aguascalientes",
  "Instituto Tecnológico de Chihuahua",
  "Instituto Tecnológico de Ciudad Juárez",
  "Instituto Tecnológico de Estudios Superiores de Monterrey Campus Chihuahua(ITESM Chihuahua)",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Ciudad Juárez)",
  "Universidad Autónoma de Chihuahua(Campus Chihuahua)",
  "Universidad Autónoma de Ciudad Juárez",
  "Universidad Tecmilenio(Campus Chihuahua)",
  "Universidad Tecmilenio(Campus Ciudad Juárez)",
  "Universidad Tecnológica de Ciudad Juárez",
  "University of Texas El Paso(UTEP)",
  "Universidad Vizcaya de Las Américas Campus Ciudad Juárez",
  "Universidad Autónoma de Chihuahua(Campus Ciudad Juarez)",
  "Otra Universidad de Chihuahua",
  "Instituto Tecnológico de Estudios Superiores de Occidente - ITESO",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Guadalajara)",
  "Universidad Autónoma de Guadalajara - UAG",
  "Universidad de Guadalajara - UdG",
  "Universidad del Valle de Atemajac - UNIVA",
  "Universidad Panamericana(Campus Guadalajara)",
  "Universidad Tecmilenio(Campus Guadalajara)",
  "Universidad Tecnológica de México - UNITEC(Campus Guadalajara)",
  "Otra Universidad de Jalisco",
  "Instituto Tecnológico de Tepic",
  "Universidad Autónoma de Chihuahua(Campus Chihuahua)",
  "Universidad Autónoma de Ciudad Juárez",
  "Universidad Tecmilenio(Campus Chihuahua)",
  "Universidad Tecmilenio(Campus Ciudad Juárez)",
  "Universidad Tecnológica de Ciudad Juárez",
  "University of Texas El Paso(UTEP)",
  "Universidad Vizcaya de Las Américas Campus Ciudad Juárez",
  "Universidad Autónoma de Chihuahua(Campus Ciudad Juarez)",
  "Otra Universidad de Chihuahua",
  "Instituto Tecnológico de Estudios Superiores de Occidente - ITESO",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Guadalajara)",
  "Universidad Autónoma de Guadalajara - UAG",
  "Universidad de Guadalajara - UdG",
  "Universidad del Valle de Atemajac - UNIVA",
  "Universidad Panamericana(Campus Guadalajara)",
  "Universidad Tecmilenio(Campus Guadalajara)",
  "Universidad Tecnológica de México - UNITEC(Campus Guadalajara)",
  "Otra Universidad de Jalisco",
  "Instituto Tecnológico de Tepic",
  "Universidad Autónoma de Nayarit",
  "Universidad del Valle de Matatipac",
  "Universidad Tecnológica de Nayarit",
  "Otra Universidad de Nayarit",
  "Otra Universidad de Colima",
  "Universidad de Celaya",
  "Universidad de León Plantel López Mateos",
  "Universidad Continente Americano Plantel Celaya ",
  "Universidad Latina de México ",
  "Instituto Tecnológico de Celaya",
  "Universidad Tecnológica del Norte de Guanajuato",
  "UDHI Universidad Dolores Hidalgo",
  "Centro de Investigación en Matemáticas - CIMAT",
  "Escuela Normal Superior Oficial de Guanajuato        ",
  "Instituto Tecnológico Superior de Guanajuato - ITESG",
  "Universidad de Guanajuato",
  "Universidad de León(Campus Guanajuato)",
  "Universidad Santa fe",
  "UG Campus Guanajuato",
  "Universidad de Guanajuato(Campus Irapuato - Salamanca)",
  "Universidad de La Salle Bajío, Plantel Salamanca",
  "Instituto Tecnológico de León",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus León)",
  "Universidad Santa fe",
  "UG Campus Guanajuato",
  "Universidad de Guanajuato(Campus Irapuato - Salamanca)",
  "Universidad de La Salle Bajío, Plantel Salamanca",
  "Instituto Politécnico Nacional (Campus Guanajuato)",
  "Instituto Tecnológico de León",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus León)",
  "Universidad de Guanajuato(Campus León)",
  "Universidad la Salle Bajío",
  "Universidad del Valle de Atemajac - UNIVA(Campus León)",
  "Universidad del Valle de México - UVM(Campus León)",
  "Universidad Estudios Profesionales de Ciencias y Artes - EPCA",
  "Universidad Iberoamericana(Campus León)",
  "Universidad Tecnológica de León",
  "Universidad Tecnológica de México - UNITEC(Campus León)",
  "EDUCEM Instituto Mexicano del Centro de México",
  "Universidad Politécnica delBicentenario",
  "Otra Universidad de Guanajuato",
  "Instituto Politécnico Nacional - ESCA",
  "Instituto Politécnico Nacional - UPIICSA",
  "Universidad del Valle de México - UVM(Campus San Rafael)",
  "Universidad Justo Sierra(Campus Cien metros)",
  "Universidad Simón Bolivar",
  "Universidad del Pedregal",
  "Centro De Estudios Superiores En Ciencias Jurídicas Y Criminológicas(Cescijuc)",
  "Tecnológico Nacional De México(Tecnm)",
  "Centro Universitario San Angel",
  "Universidad Chapultepec",
  "Universidad De Ciencias Y Administración(Ucad)",
  "Universidad Del Valle De México(Uvm) Chapultepec",
  "Universidad Del Valle De México(Uvm) Hospital Veterinario",
  "Universidad Del Valle De México(Uvm) Roma",
  "Universidad de Insurgentes",
  "Universidad Tecnológica de México - UNITEC",
  "Centro de Estudios Superiores de San Ángel - CESSA",
  "Colegio de México A.C.",
  "ITAM - Instituto Tecnológico Autónomo de México",
  "Universidad Anáhuac(Todos los campus CDMX)",
  "Universidad Autónoma de la Ciudad de México",
  "Universidad CNCI",
  "Universidad Iberoamericana",
  "Universidad Motolinía del Pedregal",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus CCM y Santa Fe)",
  "Universidad Estatal Del Valle De Ecatepec(Uneve)",
  "Universidad Icel",
  "Universidad José Vasconcelos",
  "Universidad De Londres(Udlondres)",
  "Instituto Tecnológico de Oaxaca(ITO)",
  "Universidad Anáhuac(Campus Oaxaca)",
  "Universidad Autonoma Benito Juarez de Oaxaca(UABJO)",
  "Universidad del Mar(UMAR)",
  "Universidad José Vasconcelos de Oaxaca(UNIVAS)",
  "Universidad La Salle Oaxaca",
  "Universidad Regional del Sureste",
  "Universidad Tecnológica de la Mixteca",
  "Universidad Tecnológica de la Sierra Sur de Oaxaca(UTSSO)",
  "Universidad Anáhuac(Campus Oaxaca)",
  "Universidad Autonoma Benito Juarez de Oaxaca(UABJO)",
  "Universidad del Mar(UMAR)",
  "Universidad José Vasconcelos de Oaxaca(UNIVAS)",
  "Universidad La Salle Oaxaca",
  "Universidad Regional del Sureste",
  "Universidad Tecnológica de la Mixteca",
  "Universidad Tecnológica de la Sierra Sur de Oaxaca(UTSSO)",
  "Universidad Tecnológica de los Valles Centrales de Oaxaca(UTVCO)",
  "Otra Universidad de Oaxaca",
  "Benemérita Universidad Autónoma de Puebla - BUAP",
  "CINEMA",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Puebla)",
  "Otra Universidad de Puebla",
  "Universidad Anáhuac Puebla",
  "Universidad Cuauhtémoc",
  "Universidad de las Américas - UDLAP(Campus Puebla)",
  "Universidad del Valle de Puebla - UVP",
  "Universidad Iberoamericana(Campus Puebla)",
  "Universidad Interamericana",
  "Universidad Popular Autónoma del Estado de Puebla - UPAEP",
  "Universidad Politecnica Metropolitana de Puebla",
  "Instituto Tecnologico de Puebla",
  "Universidad Iberoamericana",
  "UVP Campus tehuacan",
  "Universidad Autónoma de Tlaxcala",
  "Universidad del Altiplano",
  "Instituto Tecnológico de Tlaxcala",
  "Universidad Politécnica de Tlaxcala",
  "Otra universidad de Tlaxcala",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Querétaro)",
  "Universidad Politécnica de Santa Rosa Jauregui",
  "Universidad Tecnológica de Querétaro",
  "Universidad Tecnológica de San Juan del Río",
  "Universidad Autónoma de Querétaro",
  "Universidad Politécnica de Querétaro",
  "Universidad de Arkansas",
  "Universidad Mondragón",
  "Universidad Humánitas",
  "Universidad Cuahutémoc ",
  "Instituto Tecnologico Superior de Huichapan",
  "Otra Universidad de Querétaro",
  "Escuela Libre de Derecho - Sinaloa",
  "Universidad Autónoma de Occidente - Sinaloa",
  "Universidad del Valle del Fuerte - Sinaloa",
  "Universidad San Miguel - Sinaloa",
  "Universidad Autónoma de Sinaloa",
  "Instituto Tecnológico de Culiacán",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Sinaloa)",
  "Universidad Tecmilenio(Campus Sinaloa)",
  "Instituto de Estudios Superiores de Los Mochis(Colegio Mochis)",
  "Instituto Tecnológico de Los Mochis - ITLM",
  "Universidad Autónoma de Durango(Campus Los Mochis)",
  "Universidad Autónoma de Sinaloa - UAS(Unidad Los Mochis)",
  "Universidad de Los Mochis",
  "Otra Universidad de Sinaloa",
  "Instituto Tecnológico de Hermosillo",
  "Instituto Tecnológico de Sonora(Campus Ciudad Obregón)",
  "Instituto Tecnológico Superior de Cajeme",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey(Campus Hermosillo)",
  "Universidad de Sonora(campus Ciudad Obregón)",
  "Universidad de Sonora(campus Hermosillo)",
  "Universidad del Valle de México - UVM(Campus Hermosillo)",
  "Universidad Estatal de Sonora",
  "Universidad Interamericana para el Desarrollo - UNID(Campus Ciudad Obregón)",
  "Universidad La Salle Noroeste",
  "Universidad Tecmilenio(Campus Hermosillo)",
  "Universidad Tecnológica de Hermosillo",
  "Universidad Unilider - Sonora",
  "Otra Universidad de Sonora",
  "Universidad Autónoma de Nuevo León - UANL(Campus Ciudad Univesitaria)",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey",
  "Universidad Tecmilenio(Campus Monterrey)",
  "Universidad Regiomontana - U - ERRE",
  "Universidad Autónoma de Nuevo León - UANL(Campus Mederos)",
  "Universidad Autónoma de Nuevo León - UANL(Campus Ciudad Universitaria)",
  "Universidad Autónoma de Nuevo León - UANL(Campus Ciencias Agropecuarias)",
  "Universidad Tecnológica de Nuevo Laredo - UTNL",
  "Facultad Libre de Derecho de Monterrey",
  "Universidad Autónoma de Nuevo León - UANL(Campus Salud)",
  "Universidad de Creatividad e Innovación Humana(CREA)",
  "Universidad de Monterrey - UDEM",
  "Otra Universidad de Nuevo León",
  "Instituto Tecnológico de La Laguna",
  "Universidad Tecnológica de Torreón",
  "Universidad Tecmilenio(Campus Laguna)",
  "Universidad Autónoma de Coahuila",
  "Universidad Autónoma de La Laguna",
  "Otra Universidad de Coahuila",
  "Instituto Universitario Franco Inglés de México",
  "Escuela Bancaria y Comercial Campus Toluca y a nivel nacional",
  "Campus Universitario SIGLO XXI - Toluca",
  "Universidad Mexiquense - Toluca",
  "Instituto Tecnológico de Estudios Superiores de Monterrey campus Toluca",
  "Instituto Tecnológico de Toluca",
  "Centro Universitario Ixtlahuaca",
  "Universidad Autónoma del Estado de México",
  "Universidad Autónoma Metropolitana - UAM(Lerma)",
  "Escuela Bancaria y Comercial - EBC(Campus Toluca)",
  "Instituto Franco Inglés de México",
  "Universidad Bancaria de México(Campus Teloyucán)",
  "Universidad de Cuatitlán Izcalli",
  "Universidad del Valle de México - UVM(Campus Lago de Guadalupe)",
  "Universidad del Valle de México - UVM(Campus Lomas Verdes)",
  "Universidad del Valle de México - UVM(Campus Toluca)",
  "Universidad del Valle de Toluca - UVT",
  "Universidad Latinoamericana Metepec",
  "Universidad Tecmilenio(Campus Cuautitlán Izcalli)",
  "Universidad Tecmilenio(Campus Toluca)",
  "Universidad Univer Milenium",
  "Campus Universitario Siglo XXI",
  "Otra universidad del Estado de Mexico",
  "Escuela Bancaria Comercial - EBC",
  "Facultad Libre de Derecho de Monterrey",
  "Universidad del Claustro de Sor Juana",
  "Universidad Tecnológica Americana - UTECA",
  "Universidad Nacional Autónoma de México - UNAM",
  "Universidad de la Comunicación",
  "Universidad Autónoma Metropolitana - UAM(Xochimilco)",
  "Universidad Autónoma Metropolitana - UAM(Cuajimalpa)",
  "Universidad Autónoma Metropolitana - UAM(Iztapalapa)",
  "Universidad Pedagógica Nacional(Campus Ciudad de México)",
  "Universidad Westhill",
  "UNAM - Facultades de Estudios Superiores",
  "UNAM - Facultad de Artes y Diseño",
  "Universidad Autónoma Metropolitana(Uam) Iztapalapa",
  "Universidad Tecmilenio(Campus Cetrería Y Reforma)",
  "Universidad Latinoamericana",
  "Centro de Estudios Universitarios en Ciencias de la Comunicación - CECC",
  "Universidad del Desarrollo Empresarial y Pedagógico",
  "Universidad del Valle de México - UVM(Campus Coyoacán)",
  "Universidad del Valle de México - UVM(Campus Tlalpan)",
  "Universidad Intercontinental",
  "Universidad Panamericana(UP)",
  "Centro Universitario de Mercadotecnia y Publicidad",
  "Centro de Investigación y Docencias Económicas",
  "Universidad Multicultural Cude",
  "Universidad Tres Culturas",
  "Universidad Unisite",
  "Universidad Lucerna",
  "Universidad Mexiquense Del Bicentenario(Umb)",
  "Hispanoamericana - CDMX",
  "Instituto De Estudios Superiores De Ingeniería(Iesi)",
  "Centro Universitario Incarnate Word",
  "Universidad de la Veracruz(Campus Zacatecas)",
  "Universidad Tecnológica del Estado de Zacatecas - UTEZ",
  "Tec de Monterrey campus Zacatecas",
  "Universidad de la Vera - cruz",
  "Universidad Autónoma de Zacatecas",
  "UNID Campus Zacatecas",
  "Universidad Autónoma de Durango campus Zacatecas",
  "IZEU Campus Zacatecas",
  "IZEU Campus Fresnillo",
  "Universidad Autónoma de Durango(campus Fresnillo)",
  "UNID Campus Fresnillo",
  "ITZ Campus Zacatecas",
  "Otra Universidad de Zacatecas",
  "UTEL",
  "UAM Azcapotzalco",
  "Otra universidad de CDMX",
  "Otra universidad de Baja California",
  "Otra universidad de Baja California Sur",
  "Otra universidad de Campeche",
  "Otra universidad de Chiapas",
  "Universidad Tecnológica de Rodeo",
  "Otra universidad de Durango",
  "Otra universidad de Guerrero",
  "Otra universidad de Hidalgo",
  "Otra universidad de Morelos",
  "Otra universidad de Michoacan",
  "Otra universidad de Quintana Roo",
  "Otra universidad de Tabasco",
  "Otra universidad de Tamaulipas",
  "Otra universidad de Veracruz",
  "Otra universidad de Yucatan",
];
